Update models
eclipse-opensmartclide/smartclide-smart-assistant pull request #13
Opened 2023-02-13 16:53 UTC by Zakieh2020

2023-02-13 17:18 UTC, schlotze requested changes

2023-02-13 17:18 UTC, schlotze commented on smartclide-dle-models/serviceclassification/servclassify/README.md
> +These models need a  gateway between the trained models and user interfaces. [smartclide-dle](https://github.com/eclipse-researchlabs/smartclide-smart-assistant/tree/main/smartclide-dle) component pr
should be: https://github.com/eclipse-opensmartclide/smartclide-smart-assistant/tree/main/smartclide-dle

2023-02-14 00:06 UTC, schlotze approved these changes

2023-02-14 07:36 UTC, deanone approved these changes

2023-02-14 08:56 UTC, merged